In [2]:
import pandas as pd

interview_data=pd.read_excel('deduplicated_tech_interview_questions.xlsx')

In [3]:
interview_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1458 entries, 0 to 1457
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   question  1458 non-null   object
 1   category  1458 non-null   object
dtypes: object(2)
memory usage: 22.9+ KB


In [4]:
interview_data['category'].value_counts()

category
백엔드           691
데이터 사이언티스트    248
프론트엔드         228
데이터 엔지니어      151
데이터 분석가       140
Name: count, dtype: int64

In [5]:
from konlpy.tag import Okt


okt=Okt()
def okt_tokenizer(sentence):
    okt_token=okt.morphs(sentence)
    return okt_token

okt_tokenizer(interview_data.iloc[0,0])



['tcp', '/', 'udp', '의', '차이점', '을', '설명', '하라']

In [6]:
interview_data['question']= interview_data['question'].apply(lambda x: str(x) if isinstance(x, (int, float)) else x)

In [7]:
interview_data['question'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1458 entries, 0 to 1457
Series name: question
Non-Null Count  Dtype 
--------------  ----- 
1458 non-null   object
dtypes: object(1)
memory usage: 11.5+ KB


In [8]:
type(interview_data['question'].iloc[0])

str

In [9]:
question_cleasinged=interview_data['question'].values.astype('str')

In [10]:
question_cleasinged

array(['tcp/udp의 차이점을 설명하라', '흐름제어기법중 슬라이딩 윈도우 방식에대해 설명하라',
       '브라우저에 네이버홈페이지 url을 입력했을때 일어나는 과정을 설명해라', ...,
       '어떤 정보들이 개인정보에 해당할까요? ID는 개인정보에 해당할까요? 이를 어기지 않는 합법적 방법으로 식별하고 싶으면 어떻게 해야할까요?',
       '국내 개인 정보 보호 현황에 대한 견해는 어떠한지요? 만약 사업을 진행하는데 장애요소로 작용한다면, 이에 대한 해결 방안은 어떤 것이 있을까요?',
       '제3자 쿠키는 왜 문제가 되나요?'], dtype='<U192')

In [11]:
stop_words=pd.read_csv('korean_stopwords.txt')

In [12]:
stop_words_interview=stop_words['불용어'].tolist()
stop_words_interview

['진짜',
 '생각',
 '이제',
 '보고',
 '완전',
 '아',
 '휴',
 '어',
 '나',
 '따라',
 '의해',
 '을',
 '를',
 '에',
 '의',
 '가',
 '으로',
 '로',
 '에게',
 '의거하여',
 '근거하여',
 '입각하여',
 '기준으로',
 '예하면',
 '예를 들면',
 '예를 들자면',
 '저',
 '다른',
 '물론',
 '또한',
 '그리고',
 '비길수 없다',
 '해서는 안된다',
 '만이 아니다',
 '만은 아니다',
 '막론하고',
 '관계없이',
 '그치지 않다',
 '그러나',
 '그런데',
 '하지만',
 '든간에',
 '설사',
 '비록',
 '더라도',
 '아니면',
 '만 못하다',
 '하는 편이 낫다',
 '향하여',
 '향해서',
 '향하다',
 '쪽으로',
 '틈타',
 '이용하여',
 '타다',
 '오르다',
 '제외하고',
 '이 외에',
 '이 밖에',
 '하여야',
 '비로소',
 '한다면 몰라도',
 '외에도',
 '이곳',
 '여기',
 '부터',
 '기점으로',
 '따라서',
 '할 생각이다',
 '하려고하다',
 '이리하여',
 '그리하여',
 '그렇게 함으로써',
 '하지만',
 '일때',
 '할때',
 '앞에서',
 '중에서',
 '보는데서',
 '으로써',
 '로써',
 '까지',
 '일것이다',
 '반드시',
 '한다면',
 '등',
 '등등',
 '제',
 '겨우',
 '단지',
 '다만',
 '할뿐',
 '대해서',
 '대하여',
 '대하면',
 '훨씬',
 '얼마나',
 '얼마만큼',
 '얼마큼',
 '남짓',
 '여',
 '얼마간',
 '약간',
 '다소',
 '좀',
 '조금',
 '다수',
 '몇',
 '얼마',
 '지만',
 '하물며',
 '또한',
 '그러나',
 '그렇지만',
 '하지만',
 '이외에도',
 '대해 말하자면',
 '뿐이다',
 '다음에',
 '반대로',
 '반대로 말하자면',
 '이와 반대로',
 '만약',
 '그렇지않으면',
 '툭

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer


tfidf=TfidfVectorizer(tokenizer=okt_tokenizer,ngram_range=(1,2),stop_words=stop_words_interview ,lowercase=False,)
tfidf.fit(question_cleasinged)
tfidf_interview_data=tfidf.transform(question_cleasinged)
tfidf_interview_data

c:\Users\82106\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:521: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\82106\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:406: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['\t', '가서', '각하', '간', '같다면', '같은', '같이', '거나', '걸', '견지', '결론', '고려', '곳', '공동', '관', '관계', '관련', '구체', '그러한', '그런', '그럼에도', '그렇게', '그치지', '근거', '기대', '기점', '기준', '김', '까닭', '나머지', '남', '낫다', '낼', '년도', '누가', '다', '다시', '달려', '답', '대로', '대하', '더', '더욱이', '도', '동시', '됏', '되는', '되다', '되면', '되어', '된', '된다', '될것이다', '두번째', '뒤', '든', '든지', '들면', '들자면', '듯', '따르는', '따름', '때문', '라', '라도', '라면', '리하', '마자', '막론', '만', '만으로', '만은', '만이', '만큼', '만하', '많은', '말', '면', '모른다', '몰라도', '몰랏다', '못', '바', '바꿔', '밖에', '반대', '방면', '번째', '보다', '보아', '본대', '불구', '비', '비교', '비길수', '비추어', '뿐', '상대', '서', '서술', '수', '시작', '시초

<1458x10049 sparse matrix of type '<class 'numpy.float64'>'
	with 22289 stored elements in Compressed Sparse Row format>

In [14]:
tfidf_interview_data.shape

(1458, 10049)

In [15]:
tfidf_interview_data.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [16]:
from sklearn.preprocessing import LabelEncoder

category=interview_data['category'].values
# LabelEncoder를 객체로 생성한 후 , fit( ) 과 transform( ) 으로 label 인코딩 수행. 
encoder = LabelEncoder()
encoder.fit(category)#리스트 내용을 학습
category_encoded = encoder.transform(category)#숫자로 변환
print('인코딩 변환값:',category_encoded)

인코딩 변환값: [3 3 3 ... 3 3 3]


In [17]:
interview_data['category'].value_counts().index

Index(['백엔드', '데이터 사이언티스트', '프론트엔드', '데이터 엔지니어', '데이터 분석가'], dtype='object', name='category')

In [18]:
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['데이터 분석가' '데이터 사이언티스트' '데이터 엔지니어' '백엔드' '프론트엔드']


In [19]:
print('디코딩 원본 값:',encoder.inverse_transform([0,1,2,3,4]))

디코딩 원본 값: ['데이터 분석가' '데이터 사이언티스트' '데이터 엔지니어' '백엔드' '프론트엔드']


In [20]:
category_encoded

array([3, 3, 3, ..., 3, 3, 3])

In [21]:
interview_data['category_encoded']=category_encoded

In [22]:
interview_data

question category  \
0                                    tcp/udp의 차이점을 설명하라      백엔드   
1                           흐름제어기법중 슬라이딩 윈도우 방식에대해 설명하라      백엔드   
2                브라우저에 네이버홈페이지 url을 입력했을때 일어나는 과정을 설명해라      백엔드   
3                                      OSI 7계층에대해 설명하여라      백엔드   
4                                         Restful API란?      백엔드   
...                                                 ...      ...   
1453    인터뷰나 강의에 활용하기 위한 백데이터는 어느 수준까지 일반화 해서 사용해야 할까요?    프론트엔드   
1454  고객사가 우리와 일하고 싶은데 현재는 capa가 되지 않습니다. 어떻게 대처해야 할까요?    프론트엔드   
1455  어떤 정보들이 개인정보에 해당할까요? ID는 개인정보에 해당할까요? 이를 어기지 않...      백엔드   
1456  국내 개인 정보 보호 현황에 대한 견해는 어떠한지요? 만약 사업을 진행하는데 장애요...      백엔드   
1457                                 제3자 쿠키는 왜 문제가 되나요?      백엔드   

      category_encoded  
0                    3  
1                    3  
2                    3  
3                    3  
4                    3  
...                ...  
1453                 4  
1454                 4  
1455                 3  
1456                 3  
1457                 3  

[1458 rows x 3 columns]

In [23]:
tfidf_interview_data.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])