In [32]:
import pandas as pd

interview_data=pd.read_excel('deduplicated_tech_interview_questions.xlsx')

In [8]:
interview_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1497 entries, 0 to 1496
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   question  1496 non-null   object
 1   category  1496 non-null   object
dtypes: object(2)
memory usage: 23.5+ KB


In [33]:
interview_data['category'].value_counts()

category
백엔드           691
데이터 사이언티스트    248
프론트엔드         228
데이터 엔지니어      151
데이터 분석가       140
Name: count, dtype: int64

In [34]:
from konlpy.tag import Okt


okt=Okt()
def okt_tokenizer(sentence):
    okt_token=okt.morphs(sentence)
    return okt_token

okt_tokenizer(interview_data.iloc[0,0])



['tcp', '/', 'udp', '의', '차이점', '을', '설명', '하라']

In [35]:
interview_data['question']= interview_data['question'].apply(lambda x: str(x) if isinstance(x, (int, float)) else x)

In [36]:
interview_data['question'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1458 entries, 0 to 1457
Series name: question
Non-Null Count  Dtype 
--------------  ----- 
1458 non-null   object
dtypes: object(1)
memory usage: 11.5+ KB


In [37]:
type(interview_data['question'].iloc[0])

str

In [38]:
question_cleasinged=interview_data['question'].values.astype('str')

In [39]:
question_cleasinged

array(['tcp/udp의 차이점을 설명하라', '흐름제어기법중 슬라이딩 윈도우 방식에대해 설명하라',
       '브라우저에 네이버홈페이지 url을 입력했을때 일어나는 과정을 설명해라', ...,
       '어떤 정보들이 개인정보에 해당할까요? ID는 개인정보에 해당할까요? 이를 어기지 않는 합법적 방법으로 식별하고 싶으면 어떻게 해야할까요?',
       '국내 개인 정보 보호 현황에 대한 견해는 어떠한지요? 만약 사업을 진행하는데 장애요소로 작용한다면, 이에 대한 해결 방안은 어떤 것이 있을까요?',
       '제3자 쿠키는 왜 문제가 되나요?'], dtype='<U192')

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer


tfidf=TfidfVectorizer(tokenizer=okt_tokenizer,ngram_range=(1,2) ,lowercase=False,)
tfidf.fit(question_cleasinged)
tfidf_interview_data=tfidf.transform(question_cleasinged)
tfidf_interview_data

c:\Users\82106\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:521: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


<1458x11312 sparse matrix of type '<class 'numpy.float64'>'
	with 34240 stored elements in Compressed Sparse Row format>

In [41]:
tfidf_interview_data.shape

(1458, 11312)

In [42]:
tfidf_interview_data.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [43]:
from sklearn.preprocessing import LabelEncoder

category=interview_data['category'].values
# LabelEncoder를 객체로 생성한 후 , fit( ) 과 transform( ) 으로 label 인코딩 수행. 
encoder = LabelEncoder()
encoder.fit(category)#리스트 내용을 학습
category_encoded = encoder.transform(category)#숫자로 변환
print('인코딩 변환값:',category_encoded)

인코딩 변환값: [3 3 3 ... 3 3 3]


In [44]:
interview_data['category'].value_counts().index

Index(['백엔드', '데이터 사이언티스트', '프론트엔드', '데이터 엔지니어', '데이터 분석가'], dtype='object', name='category')

In [45]:
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['데이터 분석가' '데이터 사이언티스트' '데이터 엔지니어' '백엔드' '프론트엔드']


In [46]:
print('디코딩 원본 값:',encoder.inverse_transform([0,1,2,3,4]))

디코딩 원본 값: ['데이터 분석가' '데이터 사이언티스트' '데이터 엔지니어' '백엔드' '프론트엔드']


In [47]:
category_encoded

array([3, 3, 3, ..., 3, 3, 3])

In [48]:
interview_data['category_encoded']=category_encoded

In [49]:
interview_data

question category  \
0                                    tcp/udp의 차이점을 설명하라      백엔드   
1                           흐름제어기법중 슬라이딩 윈도우 방식에대해 설명하라      백엔드   
2                브라우저에 네이버홈페이지 url을 입력했을때 일어나는 과정을 설명해라      백엔드   
3                                      OSI 7계층에대해 설명하여라      백엔드   
4                                         Restful API란?      백엔드   
...                                                 ...      ...   
1453    인터뷰나 강의에 활용하기 위한 백데이터는 어느 수준까지 일반화 해서 사용해야 할까요?    프론트엔드   
1454  고객사가 우리와 일하고 싶은데 현재는 capa가 되지 않습니다. 어떻게 대처해야 할까요?    프론트엔드   
1455  어떤 정보들이 개인정보에 해당할까요? ID는 개인정보에 해당할까요? 이를 어기지 않...      백엔드   
1456  국내 개인 정보 보호 현황에 대한 견해는 어떠한지요? 만약 사업을 진행하는데 장애요...      백엔드   
1457                                 제3자 쿠키는 왜 문제가 되나요?      백엔드   

      category_encoded  
0                    3  
1                    3  
2                    3  
3                    3  
4                    3  
...                ...  
1453                 4  
1454                 4  
1455                 3  
1456                 3  
1457                 3  

[1458 rows x 3 columns]

In [50]:
tfidf_interview_data.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])